name: Tech Debt/Code Improvement
description: Track existing technical debt or suggest ideas for code improvement.
labels: ["Type: Tech Debt"]
body:
  - type: textarea
    id: problem-details
    attributes:
      label: Do you have a suggestion for code improvement or tracking existing technical debt? Please describe.
      description: A clear and concise description of what the current tech debt or code deficiency is.
      placeholder: e.g. Bumping a dependency, Refactoring, etc.
  - type: textarea
    id: solution-details
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: Ex. The dependency on [...] should be bumped to [...] because [...]
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, screenshots etc. related to the request
